# Generated by Django 5.1.2 on 2024-12-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='crm',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='documento',
            field=models.IntegerField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='endereco',
            field=models.TextField(max_length=100),
        ),
    ]
